#!/bin/bash

if [ $# == 0 ]
then
    echo 'Base';
    echo '--load    - load example contoller,model,config,view,www';
    echo '--remove  - remove folder example in Fork/bin';
    echo '--clear   - remove fork test files';
    echo '--create {Type} {Name}  - create Controller or Model or Route file';

    echo 'Module';
    echo '--module  - show all module in Fork';    
    echo '--include {Module} - include module in Fork';
    echo '--disable {Module} - disable module in Fork';
else
    #   if($argv[1] == '--load'){
    #    $LoadSuccesful = true;

   
    echo "Folder bin/example/config loading";
    
    #	exec('cp bin/example/config/* config/',$Output,$ReturnConfig);
    #	if($ReturnConfig == 1){
    echo "Error load config files";
    
    #	    $LoadSuccesful = false;
    #	}else{
    echo "Folder bin/example/config load";
    
    #	}

    
    echo "Folder bin/example/controllers loading";
    
    #	exec('cp bin/example/controllers/* controllers/',$Output,$ReturnController);
    #	if($ReturnController == 1){
    echo "Error load controllers files";
    
    #	    $LoadSuccesful = false;
    #	}else{
    echo "Folder bin/example/controllers load";
    
    #	}

    
    echo "Folder bin/example/models loading";
    
    #	exec('cp bin/example/models/* models/',$Output,$ReturnModel);
    #	if($ReturnModel == 1){
    echo "Error load models files";
    
    #	    $LoadSuccesful = false;
    #	}else{
    echo "Folder bin/example/models load";
    
    #	}

    
    echo "Folder bin/example/views loading";
    
    #	exec('cp bin/example/views/* views/',$Output,$ReturnView);
    #	if($ReturnView == 1){
    echo "Error load views files";
    
    #	    $LoadSuccesful = false;
    #	}else{
    echo "Folder bin/example/views load";
    
    #	}


    
    echo "Directory example load successful";
    
    #    }else if($argv[1] == '--remove'){
    echo "Folder bin/example removing";
    #	exec('rm -r ./bin/example');
    #	exec();
    
    echo "Remove complete";
    #    }else{
    echo 'Error argument';
    #    }
    #} 
fi
