#!/bin/bash

if [ $# == 0 ]
then
    echo 'Base'
    echo '--clear   - remove fork test files'
    echo '--create {Type} {Name}  - create Controller or Model or Route file'
    echo '--install - install all packate and programme for Fork'
    echo '--migration - Migration in database'

    echo 'Module'
    echo '--module  - show all module in Fork'
    echo '--include {Module} - include module in Fork'
    echo '--disable {Module} - disable module in Fork'
    exit;
fi

if [ $1 == '--clear' ]
then
    rm README.md
    rm Fork.conf
    rm controllers/ForkController.php
    rm models/ForkModel.php
    rm route/ForkRoute.php
    rm config/ForkConfig.php
    rm views/index.fork.html.php

elif [ $1 == '--create' ] && [ $2 != '' ] && [ $3 != '' ]
then
    if  [ $2 == '-controller' ] 
    then
	cp bin/Routine/Controller.php controllers/
	mv controllers/Controller.php controllers/$3.php 
    elif [ $2 == '-model' ] 
    then
	cp bin/Routine/Model.php models/
	mv models/Model.php models/$3.php 
    elif [ $2 == '-route' ] 
    then
	cp bin/Routine/Route.php route/
	mv route/Route.php route/$3.php
    elif [ $2 == '-config' ] 
    then
	cp bin/Routine/Config.php config/
	mv config/Config.php config/$3.php 
    else 
	echo "Invalid create type"
    fi
elif [ $1 == '--migration' ]
then
    echo 'php'
elif [ $1 == '--module' ]
then
     find bin/ -mindepth 1 -maxdepth 1 -type d  \( ! -iname ".*" \) #| sed 's|^\./||g'
     
elif [ $1 == '--enable' ]
then
    echo 'enable'
elif [ $1 == '--disable' ]
then
    echo 'disable'

else
    echo 'Invalid command'
fi

